# Generated by Django 2.0.2 on 2018-02-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('created_data', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Данные пользователей',
                'verbose_name': 'Данные пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserData')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'verbose_name': 'Профиль пользователя',
            },
        ),
    ]
