# Generated by Django 2.0.2 on 2018-02-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata_email_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email_is_active',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
