# Generated by Django 2.0.2 on 2018-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180214_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email_is_active',
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_is_confirm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
