# Generated by Django 2.0.2 on 2018-02-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180214_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='login',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True),
        ),
    ]
